import { Job } from '../../interfaces/detail';
export const jobs: Job[] = [
    {
        id: '1',
        title: 'Software Engineer',
        description: 'Develop and maintain software applications.',
        salary: 80000,
        status: 'open',
        employer: { profile: 'profileA.png', name: 'Company A', telephone: '123-456-7890' },
    },
    {
        id: '2',
        title: 'Data Scientist',
        description: 'Analyze and interpret complex data sets.',
        salary: 85000,
        status: 'open',
        employer: { profile: 'profileB.png', name: 'Company B', telephone: '123-456-7891' },
    },
    {
        id: '3',
        title: 'Product Manager',
        description: 'Lead product development teams.',
        salary: 90000,
        status: 'open',
        employer: { profile: 'profileC.png', name: 'Company C', telephone: '123-456-7892' },
    },
    {
        id: '4',
        title: 'UX Designer',
        description: 'Design user-friendly interfaces.',
        salary: 75000,
        status: 'open',
        employer: { profile: 'profileD.png', name: 'Company D', telephone: '123-456-7893' },
    },
    {
        id: '5',
        title: 'DevOps Engineer',
        description: 'Maintain CI/CD pipelines.',
        salary: 95000,
        status: 'open',
        employer: { profile: 'profileE.png', name: 'Company E', telephone: '123-456-7894' },
    },
    {
        id: '6',
        title: 'QA Tester',
        description: 'Test software for bugs and issues.',
        salary: 65000,
        status: 'open',
        employer: { profile: 'profileF.png', name: 'Company F', telephone: '123-456-7895' },
    },
    {
        id: '7',
        title: 'System Administrator',
        description: 'Manage IT infrastructure.',
        salary: 70000,
        status: 'open',
        employer: { profile: 'profileG.png', name: 'Company G', telephone: '123-456-7896' },
    },
    {
        id: '8',
        title: 'Marketing Specialist',
        description: 'Develop marketing strategies.',
        salary: 72000,
        status: 'open',
        employer: { profile: 'profileH.png', name: 'Company H', telephone: '123-456-7897' },
    },
    {
        id: '9',
        title: 'Sales Manager',
        description: 'Lead sales teams and strategies.',
        salary: 85000,
        status: 'open',
        employer: { profile: 'profileI.png', name: 'Company I', telephone: '123-456-7898' },
    },
    {
        id: '10',
        title: 'HR Manager',
        description: 'Manage HR functions and policies.',
        salary: 80000,
        status: 'open',
        employer: { profile: 'profileJ.png', name: 'Company J', telephone: '123-456-7899' },
    },
];
